"use strict";
exports.__esModule = true;
var loc = require("./src/app/drawingboard/state/stateLocator");
exports.axCircAdd = "circ/add";
exports.axCircEdit = "circ/edit";
exports.axCircDel = "circ/delete";
exports.axCircClr = "circ/clear";
exports.axSelAdd = "sel/add";
exports.axSelClr = "sel/clear";
exports.types = [exports.axCircAdd, exports.axCircEdit, exports.axCircDel, exports.axCircClr];
loc.StateLocator.register(loc.LocatorEntry.create("one", exports.types, null));
console.log("items", loc.StateLocator.locate("circ"));
exports.axRectAdd = "rect/add";
exports.axRectEdit = "rect/edit";
exports.axRectDel = "rect/delete";
exports.axRectClr = "rect/clear";
var types2 = [exports.axRectAdd, exports.axRectEdit, exports.axRectDel, exports.axRectClr, exports.axSelAdd, exports.axSelClr];
loc.StateLocator.register(loc.LocatorEntry.create("two", types2, null));
console.log("circ items after adding type2", loc.StateLocator.locate("circ"));
console.log("rect items after adding type2", loc.StateLocator.locate("rect"));
